### ISSUE TITLE
Statistics: Do not have Total number of applicants by Interview Stages (only)

### ISSUE THREAD

**Issue by hansneddyanto** [AY2425S1-CS2103-F09-3/tp#139]
Total of N across ALL jobcodes, total of TP across ALL jobcodes, etc.

Total N: 43
    - swe2024: 5
    - dsa2024: 10
    - lse2024: 28
Total TP: 5
...

**Comment by vicelyav** [comment]
Put it under the total number of applicants across all stages, before breaking down

**Comment by vicelyav** [comment]
Future enhancement

**Comment by hazzle23** [comment]
the one that hans put is stats t/
the one that is already implemented is stats j/
