### ISSUE TITLE
add: error message is not specific

### ISSUE THREAD

**Issue by hansneddyanto** [AY2425S1-CS2103-F09-3/tp#151]
add n/   drag  mE  to HELL t/tp p / 995  e/dragmetohell@email.com

Invalid command format! 
add: Adds a person to the address book. Parameters: n/NAME p/PHONE e/EMAIL j/JOB CODE t/TAG
Example: add n/John Doe p/98765432 e/johnd@example.com j/SWE2024 t/N 

Users do not know where is the mistake

**Comment by hazzle23** [comment]
Fixing error message when one compulsory field is empty
AddCommandParser.java line 40, change the MESSAGE_INVALID_COMMAND_FORMAT to something else

**Comment by hansneddyanto** [comment]
"It's missing j"
"It's missing p"

OR

"It's missing p"
"It's missing j"
