### ISSUE TITLE
Tag: Can remove whitespaces in input tag

### ISSUE THREAD

**Issue by ChinSekYi** [AY2425S1-CS2103-F09-3/tp#156]
<img width="645" alt="Screenshot 2024-10-27 at 6 22 34 PM" src="https://github.com/user-attachments/assets/43ef9075-25a2-4db0-8cf9-9e7e775e80d3">

Should users need to ownself remove the whitespaces in the tag, or we can help users remove the whitespaces by trimming?

**Comment by hazzle23** [comment]
Will trim
