### ISSUE TITLE
Sort: sort by jobcode not working

### ISSUE THREAD

**Issue by ChinSekYi** [AY2425S1-CS2103-F09-3/tp#163]
For example:
j/bbc
j/abc

sort j/ will give
j/bbc
j/abc

**Comment by hansneddyanto** [comment]
![image](https://github.com/user-attachments/assets/2696e771-34b0-4923-964a-adcb76173aaa)
Works for me tho?

**Comment by ChinSekYi** [comment]
hmm i think it occurs in combi with other fields also

**Comment by hazzle23** [comment]
> hmm i think it occurs in combi with other fields also

Hello! Could you please provide additional detail? I checked on my side and it works just like Hans' screenshot
