### ISSUE TITLE
delete: confusing feedback

### ISSUE THREAD

**Issue by hansneddyanto** [AY2425S1-CS2103-F09-3/tp#164]
There's a problem with validation when deleteCommand is used.

For example:
- delete n/hanaa p/87429101 **t/tp**
- Invalid phone number: only numeric characters and optional leading '+' are allowed.

and 

- delete n/hanaa t/tp  
- Invalid name: Only alphanumeric characters are allowed, and it should not be blank.

**Comment by vicelyav** [comment]
check the parsing of phone number
