### ISSUE TITLE
Add:  Feedback for jobcode doesn't match example in UG

### ISSUE THREAD

**Issue by ChinSekYi** [AY2425S1-CS2103-F09-3/tp#168]
<img width="844" alt="Screenshot 2024-10-27 at 6 36 10 PM" src="https://github.com/user-attachments/assets/7194d690-b186-486d-9f93-6d6ceb1d7d90">

Fields in feedback box need to match the field in UG. 
Eg, `j/JOB CODE` in feedback box should be `j/JOB_CODE_APPLIED_FOR`

**Comment by hazzle23** [comment]
I'll change the UG to be `j/JOB_CODE`
