### ISSUE TITLE
add: 'wrong' name input works

### ISSUE THREAD

**Issue by hansneddyanto** [AY2425S1-CS2103-F09-3/tp#175]
add n/87429101 ... works, even though this is an exaple of user obviously inputting phone number inside name

**Comment by hansneddyanto** [comment]
![image](https://github.com/user-attachments/assets/b50fd62f-f69e-4445-a522-eca91a8dcd98)
Here, user wrongly added tag "New" in the name, but there is no warning/blocking

**Comment by ChinSekYi** [comment]
Check if the name input is all numbers.

**Comment by ChinSekYi** [comment]
done
