### ISSUE TITLE
Email and phone: people with different name can have the same email and phone

### ISSUE THREAD

**Issue by hansneddyanto** [AY2425S1-CS2103-F09-3/tp#183]
![image](https://github.com/user-attachments/assets/6046909e-52d6-45da-8b23-63dad42b5b51)
![image](https://github.com/user-attachments/assets/605a967f-8bb2-47f9-a3df-4bffd27b012d)

Maybe user inputs information wrongly. Maybe can put warning?

**Comment by vicelyav** [comment]
we disallow duplicate email and phone 
So, 
different name cannot have the same phone and email
solve in AddCommand

**Comment by ChinSekYi** [comment]
Solved in Person.java
