### ISSUE TITLE
Email and phone: validity check

### ISSUE THREAD

**Issue by hansneddyanto** [AY2425S1-CS2103-F09-3/tp#184]
For email and phone, addressBook still accepts even though it's not valid domain and country code (@example.com and +11 is still accepted)
![image](https://github.com/user-attachments/assets/3adbdeb4-de33-4cb7-805d-cecefa08b834)

**Comment by ChinSekYi** [comment]
checking for valid country code is not in scope. 
This is mentioned in UG.
### PHONE
- Checking for valid country code is not in scope.
