### ISSUE TITLE
Phone: unclear country code

### ISSUE THREAD

**Issue by hansneddyanto** [AY2425S1-CS2103-F09-3/tp#190]
![image](https://github.com/user-attachments/assets/615e3a40-541d-4658-b927-790048f0d012)

During parsing in adding contact, and when showing the contact itself, it is unclear which one is the country code

In this case, is the country code UK (+44) or Guernsey (+44-1481)?

**Comment by ChinSekYi** [comment]
Not in scope

**Comment by vicelyav** [comment]
any phone number, remove the plus

**Comment by hansneddyanto** [comment]
use remark
