### ISSUE TITLE
Statistics: expectation

### ISSUE THREAD

**Issue by hansneddyanto** [AY2425S1-CS2103-F09-3/tp#196]
Statistics suggests that there is to be some kind of percentage, and/or data analysis (mean/median/mode), distribution, etc.

The current feature does not have this, which is important for senior HR who needs to report to the management. Current statistics feature does not address this issue for senior HR, as he/she still needs to manually count

**Comment by vicelyav** [comment]
percentage of applicants in each interview stage (regardless of job)
