### ISSUE TITLE
UI: Email

### ISSUE THREAD

**Issue by hansneddyanto** [AY2425S1-CS2103-F09-3/tp#200]
Email is not case-sensitive. It is an eyesore to seeinconsistent capitalisation in email. Will it be better to just un-capitalise emails?

![image](https://github.com/user-attachments/assets/a2fd12ca-6e78-4c78-adeb-8e8a5582b7d8)

**Comment by ChinSekYi** [comment]
domain, which is the part after @, should be case insensitive. Should be parse into lowercase. 
the part before @ should be case sensitive
