### ISSUE TITLE
sort n/ not working

### ISSUE THREAD

**Issue by hansneddyanto** [AY2425S1-CS2103-F09-3/tp#202]
Hard to remember that sort == sort n/
But sort n/ does not work

Should also just implement sort n/ ??

But then user might be confused what's the difference between sort and sort n/, and if they're the same why accept both

Maybe should just implement sort n/, and go away with sort

**Comment by vicelyav** [comment]
ok can have sort n/ 
we think that users might be stupid and try to sort name also.

**Comment by vicelyav** [comment]
need to customise the error message

e.g. : List sorted based on your selected criteria(s) 
n/
