### ISSUE TITLE
nextStage feature

### ISSUE THREAD

**Issue by hansneddyanto** [AY2425S1-CS2103-F09-3/tp#210]
Should have nextStage feature to massEdit the tag of people who move on to the next stage. The stages should have a sequence, e.g. N -> BP -> BC -> TP -> TC -> A, and R can come after any stage.

nextStage 1 3 4 5 7 will move indices 1,3,4,5,7 to the next stage

**Comment by vicelyav** [comment]
not in scope

**Comment by ChinSekYi** [comment]
Not in scope

**Comment by vicelyav** [comment]
different companies have different application process
so we shouldn't generalise one particular application flow
