### ISSUE TITLE
Can open multiple instances of the app which are not synced

### ISSUE THREAD

**Issue by hansneddyanto** [AY2425S1-CS2103-F09-3/tp#213]
Can open multiple instances of the app which are not synced. Either allow only one instance to open, or if can open multiple instances then they should be synced at all times.

![image](https://github.com/user-attachments/assets/f409b85c-3b13-41b5-9e98-607cbaaa880b)

Note: There are multiple storage: addressbook.log.0, addressbook.log.0.1, addressbook.log.0.2 
![image](https://github.com/user-attachments/assets/2884ea2f-e9a2-412f-96e0-29dfcc6a4214)

**Comment by vicelyav** [comment]
put in user guide, explain that only one instance of the app (need to check) will save the changes to addressbook. So users need to refrain from opening multiple instances of the app.
