### ISSUE TITLE
[PE-D][Tester B] Duplicate parameters allowed in Edit Command

### ISSUE THREAD

**Issue by nus-se-script** [AY2425S1-CS2103-F09-3/tp#284]
Edit Command accepts duplicate parameters, namely tag `t/` and remark `r/`. This behaviour is not stated in the UG.

When duplicate tag or remark fields are provided, the field will be updated with the parameter that appears later in the command.

E.g.: `edit 1 r/tall r/short` will update the 1st person's remark to short.

Before entering `edit` command with duplicate parameters:

![image.png](https://raw.githubusercontent.com/aldentantan/ped/main/files/6ccc3ac7-0985-4f90-b410-344b8991ee05.png)

After entering the command:

![image.png](https://raw.githubusercontent.com/aldentantan/ped/main/files/ef8778af-5bd8-4353-951a-a1e484061882.png)

-------------
Labels: `severity.Medium` `type.FunctionalityBug`
original: aldentantan/ped#6

**Comment by hansneddyanto** [comment]
change code behaviour
