### ISSUE TITLE
[PE-D][Tester B] Incorrect error message for Edit Command

### ISSUE THREAD

**Issue by nus-se-script** [AY2425S1-CS2103-F09-3/tp#286]
Command to reproduce: `edit 1 n/'O Connor`

According to UG, names can include aprostophes so `'O Connor` should be a valid name. However, the error message does not inform the user how to rectify it since it is a valid name by the documentation.

UG should state that names cannot start with special characters.

![image.png](https://raw.githubusercontent.com/aldentantan/ped/main/files/ba00e975-7d55-4fd8-bd66-a6e3e6fed0ef.png)

-------------
Labels: `severity.Medium` `type.FunctionalityBug`
original: aldentantan/ped#7

**Comment by ChinSekYi** [comment]
Is a bug. Fix validity check for name

**Comment by hansneddyanto** [comment]
UG change, error message change
