### ISSUE TITLE
[PE-D][Tester A] UG Explanation of Add format missing the optional remark 

### ISSUE THREAD

**Issue by nus-pe-script** [AY2425S1-CS2103-F09-3/tp#291]
Users are able to optionally enter remark so UG add format should specify that for clarity. 

![image.png](https://raw.githubusercontent.com/AbdulrahmanAlRammah/ped/main/files/3a85fb9b-ff61-4071-9b9a-fa3820ed3cfb.png)

![image.png](https://raw.githubusercontent.com/AbdulrahmanAlRammah/ped/main/files/dc181f6f-798f-49ba-b124-8813356d0cee.png)

-------------
Labels: `type.DocumentationBug` `severity.Low`
original: AbdulrahmanAlRammah/ped#2

**Comment by ChinSekYi** [comment]
Edit UG Page 3
