### ISSUE TITLE
[PE-D][Tester B] Delete Command parameters unclear

### ISSUE THREAD

**Issue by nus-pe-script** [AY2425S1-CS2103-F09-3/tp#293]
From the status message of Delete (seen when `delete` is entered), there are no square brackets around parameters (INDEX, n/NAME etc.). This means that the parameters are compulsory, as seen from the Features section in the UG.

However, the Delete command only accepts 1 out of the listed parameters which conflicts with the compulsory parameters explanation.

![image.png](https://raw.githubusercontent.com/aldentantan/ped/main/files/e59adb19-a3af-4ace-bc4b-430a1ab163cc.png)

-------------
Labels: `severity.Medium` `type.FeatureFlaw`
original: aldentantan/ped#10

**Comment by hansneddyanto** [comment]
Change error message(?). Add 'or'
