### ISSUE TITLE
[PE-D][Tester C] User Guide Contents Page: Improve Section Titles for Better Navigability

### ISSUE THREAD

**Issue by nus-pe-script** [AY2425S1-CS2103-F09-3/tp#294]
![Screenshot 2024-11-08 at 16.51.44.png](https://raw.githubusercontent.com/haleemairfan/ped/main/files/099ba508-9e26-44a2-ab45-fe26419a702c.png)
The current user guide content page

Description:
In the user guide's contents page, each section title currently starts with a brief description of the command (e.g., "Viewing help: help") rather than the command itself. This structure can make it harder for users to quickly locate specific commands when scanning the contents page. Reformatting the titles to start with the command name (e.g., "help: Viewing help") would improve readability and make navigation faster and more intuitive for users.

Steps to improve:
1. Reformat the section titles in the contents page to start with the command name, followed by the description. This change would enhance navigability, making it easier for users to find specific commands quickly.

-------------
Labels: `type.DocumentationBug` `severity.VeryLow`
original: haleemairfan/ped#4

**Comment by vicelyav** [comment]
UG Page 1
