### ISSUE TITLE
[PE-D][Tester A] UG Command Summary Add Command Remark not listed as optional

### ISSUE THREAD

**Issue by nus-se-script** [AY2425S1-CS2103-F09-3/tp#295]
In the command summary for the add command format r/remark is not in [ ] to indicate that it is optional. This may confuse the user who might assume it is mandatory.

![image.png](https://raw.githubusercontent.com/AbdulrahmanAlRammah/ped/main/files/d46bbdb5-ef86-47a9-ac67-ff02b090980c.png)

-------------
Labels: `type.DocumentationBug` `severity.Low`
original: AbdulrahmanAlRammah/ped#4

**Comment by ChinSekYi** [comment]
Edit UG page 8
