### ISSUE TITLE
[PE-D][Tester A] UG Blank Space after find

### ISSUE THREAD

**Issue by nus-pe-script** [AY2425S1-CS2103-F09-3/tp#303]
There is a blank space of over half a page in the find description. This can be removed by simply resizing the picture. 

![image.png](https://raw.githubusercontent.com/AbdulrahmanAlRammah/ped/main/files/5de5a810-2a4a-43d1-97ec-d012598bea46.png)

-------------
Labels: `type.DocumentationBug` `severity.VeryLow`
original: AbdulrahmanAlRammah/ped#5

**Comment by vicelyav** [comment]
UG Page 4
