### ISSUE TITLE
[PE-D][Tester A] Delete Command Multiple Parameters when no Duplicate not accepted

### ISSUE THREAD

**Issue by nus-pe-script** [AY2425S1-CS2103-F09-3/tp#310]
According to the UG command summary delete there are examples such as 3 and 4 where you are allowed to input multiple parameters of the person you are deleting but the program does not allow this (see image). This case is for people who have the same name, but even if I don't have someone with the same name I should be allowed to delete with two fields as it is still clear who I want to delete. Having to eliminate one of the fields can be too restrictive.

![image.png](https://raw.githubusercontent.com/AbdulrahmanAlRammah/ped/main/files/1531f65a-5383-417d-8dea-dc31349db90a.png)

![image.png](https://raw.githubusercontent.com/AbdulrahmanAlRammah/ped/main/files/76d3c895-89fb-4dda-9aee-99db3020c927.png)

-------------
Labels: `severity.Low` `type.FeatureFlaw`
original: AbdulrahmanAlRammah/ped#8

**Comment by vicelyav** [comment]
duPLICATE
