### ISSUE TITLE
[PE-D][Tester A] UG Edit Explanation format missing remark

### ISSUE THREAD

**Issue by nus-pe-script** [AY2425S1-CS2103-F09-3/tp#313]
The optional editing of remark is missing in the format explanation.

![image.png](https://raw.githubusercontent.com/AbdulrahmanAlRammah/ped/main/files/3052f180-20c7-4a20-b6c2-a8815b1c76a2.png)

-------------
Labels: `type.DocumentationBug` `severity.Low`
original: AbdulrahmanAlRammah/ped#10

**Comment by ChinSekYi** [comment]
Update the UG Page 3
