### ISSUE TITLE
[PE-D][Tester A] UG Delete Command Explanation has incorrect extra text

### ISSUE THREAD

**Issue by nus-se-script** [AY2425S1-CS2103-F09-3/tp#322]
It seems the last bullet point in the delete command explanation should end at former. There is some text I can't comprehend after.

![image.png](https://raw.githubusercontent.com/AbdulrahmanAlRammah/ped/main/files/8614ac6e-5377-4a06-ae62-0e0d9ecc962a.png)

-------------
Labels: `type.DocumentationBug` `severity.Low`
original: AbdulrahmanAlRammah/ped#15

**Comment by vicelyav** [comment]
UG Page 6

**Comment by hansneddyanto** [comment]
delete last bullet point
