### ISSUE TITLE
[PE-D][Tester A] DG Unclear User Story

### ISSUE THREAD

**Issue by nus-pe-script** [AY2425S1-CS2103-F09-3/tp#333]
The first user story 3rd part (so that I can) should be changed to see the details or something similar. "See the contact of every applicant" is the same as "see the list of every applicant". The reason you want to see is to see the details which I am sure is the intention but the current phrasing isn't clear.

![image.png](https://raw.githubusercontent.com/AbdulrahmanAlRammah/ped/main/files/ec5c2083-eb24-4ab3-a053-49fcdbc0b99d.png)

-------------
Labels: `type.DocumentationBug` `severity.Low`
original: AbdulrahmanAlRammah/ped#26

**Comment by ChinSekYi** [comment]
Edit DG page 11
