### ISSUE TITLE
Edit the "Editing Data" and "Archiving Data" in UG

### ISSUE THREAD

**Issue by hazzle23** [AY2425S1-CS2103-F09-3/tp#366]
![image](https://github.com/user-attachments/assets/14e744c2-8f3a-4678-b390-49008d9ceb14)

Right now
- We still have section called Archiving data files
- In section Editing the data, it is mentioned that editing data might cause app to behave unexpected way.

To do
- delete Archiving data section
- in Editing data section, we say things like "Any changes that makes the format invalid or any formatting issue differ than how the app usually save data, Talentcy will discard all" (refine my sentence ah this one rough one only)
Therefore, edit the data file only if you are **very confident** that you can update it correctly.

**Comment by hansneddyanto** [comment]
Will delete 'Furthermore, ... correctly.'
Will delete section 'Archiving data files'
